### ISSUE TITLE
Suggestion: Godot 3.0 support

### ISSUE THREAD

**Issue by zatherz** [henriquelalves/SimpleGodotCRTShader#1]

**Comment by GrandFunkR** [comment]
I love this. I hope it will be supported godot 3.0

**Comment by Seba313** [comment]
Hope to see this shader in G3.0 too :)

**Comment by MohabMohamed** [comment]
@henriquelalves can I try to implement this, please? D:

**Comment by henriquelalves** [comment]
@MohabMohamed Sure thing! Sorry I can't be more helpful, I have my hands at a lot of work right now, but if you get any questions doing it just ping me on my github account email (although everything I used to create the shader is on the README.md, haha).

If you want, you can make a PR and I'll add a Godot3 plugin folder to this repository.

**Comment by MohabMohamed** [comment]
Thanks D:

**Comment by henriquelalves** [comment]
Done by @MohabMohamed , already merged on master!
