### ISSUE TITLE
How to reuse and acreditate?

### ISSUE THREAD

**Issue by Dariasteam** [henriquelalves/SimpleGodotCRTShader#2]
I want to use this on my GPLv3 game. Can I? How do I mention you? Thank you!

**Comment by henriquelalves** [comment]
Sup!

I licensed the shader code as MIT; it means you can use it freely, no need to worry about license compatibilities (GPL is more "restrictive" than MIT, even as a Copyleft license). Just use/modify the shader at will, I'm glad it's useful to your project, hahaha. If you want to mention me (and I'm flattered if you want!), you can just mention this shader on your project README or something, if it's on GitHub!

**Comment by Dariasteam** [comment]
Oh, I am so used to read the licence at the end of the README that i looked for yours there and forgot to see if there was the file itself! Thank you so much, and of course I will mention you

**Comment by henriquelalves** [comment]
Haha, np, glad I could help!
