### ISSUE TITLE
Shader breaks in Godot 3.2

### ISSUE THREAD

**Issue by jonjondev** [henriquelalves/SimpleGodotCRTShader#6]
Today I opened a game I was working on (in Godot's new 3.2 release) which uses this project to provide a CRT effect, and found that it shows only a blank, white screen as below:
<img width="752" alt="Screen Shot 2020-01-30 at 11 48 35 am" src="https://user-images.githubusercontent.com/9414994/73410578-cb94da80-4356-11ea-9aa1-bdeff6b4932b.png">

The project can be found [here](https://github.com/J-Mo63/cyberheist).

Unsure about the reasons for the issue as yet, but posting here first to flag it on the Github.

**Comment by jonjondev** [comment]
#7 Fixes the issue above. Please action the pull request to merge it with the master branch @henriquelalves. And thank you so much for putting this project out in the wild!

**Comment by henriquelalves** [comment]
Just tested and merged both pull requests!
Thanks for making the fix and creating the issue I was unaware that there was even another pull request also fixing the Barrel effect on Godot 3.x. All should be fine now!
